spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wanted
    username: admin
    password: admin1008
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  sql:
    init:
      mode: always

logging:
  level:
    org.hibernate.SQL: DEBUG
